[package]
name = "reth-crawler-db"
version = "0.1.0"
edition = "2021"

[dependencies]
# aws
aws-config = { version = "0.56.1" }
aws-sdk-dynamodb = { version = "0.33.0" }

# types
reth-crawler-types = { path = "../../crates/types" }
